# fly.toml app configuration file generated for feuillu-newsletter on 2023-10-12T20:24:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "feuillu-newsletter"
primary_region = "cdg"


[env]
  DATABASE_URL = "file:/data/sqlite.db"
  PORT = "3000"

[mounts]
  destination = "/data"
  source = "data"

[build]
  command = "npm install"
  environment = ["NODE_ENV=production"]

[build.env]
  NODE_ENV = "production"

[build.mounts]
  source = ".env"
  destination = "/app/.env"
  type = "file"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
