# fly.toml app configuration file generated for feuillu-newsletter on 2023-10-11T16:24:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "feuillu-newsletter"
primary_region = "cdg"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
